### PR TITLE
7.x add 7.4 and 8.0

### PR DESCRIPTION
**Pull request by kporras07**
Hi @stovak 

I created a single branch with Github Actions integration to build and push both 7.4.x and 8.0.x images.

I added the needed secrets and this will be automatically pushing both to quay and Docker Hub

This will fix both #77 and #78 and it's easier to maintain.

Let me know if you need me to do any changes.

### CODE REVIEW

**Review by greg-1-anderson — CHANGES_REQUESTED** [review]
Let's change the image name to something like 7.x-php7.4 & c.

**Comment by kporras07** [comment]
@greg-1-anderson updated

**Comment by greg-1-anderson** [comment]
This looks pretty good; I just need to look up the Quay credentials so that the tests can run.

Could you update the README to describe the 7.x branch, and also include a section showing how to use this in Github actions and/or CircleCI (document image name, etc.)?

**Comment by kporras07** [comment]
@greg-1-anderson updated docs. Please review.

**Comment by kporras07** [comment]
@greg-1-anderson this is now ready and pushing from Github Actions both to quay and Docker Hub

**Review by greg-1-anderson — APPROVED** [review]

**Comment by kporras07** [comment]
I confirm that the push worked to both registries.

**Pull request merged**
