### PR TITLE
Include node components

### PR DESCRIPTION
**Pull request by greg-1-anderson**

### CODE REVIEW

**Comment by arosboro** [comment]
@greg-1-anderson I have a project that needs npm to build assets for its theme.  I'm willing to test this and report back if it is possible to do a tag on quay.io to the nodejs branch.

**Comment by greg-1-anderson** [comment]
@arosboro There is now a `nodejs` tag on quey.io: https://quay.io/repository/pantheon-public/build-tools-ci?tab=tags

The only reason it was not there before was that the build here was failing, and I didn't notice. Thanks for offering to test.

**Comment by arosboro** [comment]
Initially, I saw the following message w/ composer.  It looks like the php extensions now need to be re-enabled:

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for drupal/core 8.5.3 -> satisfiable by drupal/core[8.5.3].
>     - drupal/core 8.5.3 requires ext-gd * -> the requested PHP extension gd is missing from your system.
>   Problem 2
>     - drupal/core 8.5.3 requires ext-gd * -> the requested PHP extension gd is missing from your system.
>     - drupal/zurb_foundation 6.0.0-alpha4 requires drupal/core ~8.0 -> satisfiable by drupal/core[8.5.3].
>     - Installation request for drupal/zurb_foundation 6.0.0-alpha4 -> satisfiable by drupal/zurb_foundation[6.0.0-alpha4].
> 
>   To enable extensions, verify that they are enabled in your .ini files:
>     - 
>     - /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
>   You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

**Comment by greg-1-anderson** [comment]
@arosboro I guess the php + nodejs container does not have as many php extensions as the php base container I was using before. You could try modifying your test scripts to always call Composer with `--ignore-platform-reqs`.

I'll probably add the php extensions here in a bit, though, in case someone wants to use this container to actually run Drupal.

**Comment by arosboro** [comment]
Thanks for the workaround.  For the time being, I am committing the npm assets instead of building them in the container.  I may be able to revisit in several weeks.

**Comment by greg-1-anderson** [comment]
I added some php extensions per https://github.com/drupal-docker/php, so this will be here next time you want to try it. The container did build, but I have not confirmed that it is usable for its intended purpose. It might be better to make a multi-phase container; I don't really want to duplicate build steps from either the Drupal or the nodejs parent images.

**Comment by arosboro** [comment]
Hi @greg-1-anderson! I am successfully using the nodejs container to build assets with npm/gulp (after upgrading the npm version in my build script).  I'm running google-chrome in the container and using behat w/ the behat-drush-endpoint work I did on a Drupal 8 site for several weeks now.

Thanks for getting this out quickly and making the modifications for php.

**Comment by greg-1-anderson** [comment]
Thanks. I'm going to leave this here in case folks want to use it, but I think that the better model would be to have a separate build assets step in Circle 2 that used `circleci/php:7.1-cli-node-browsers` so that we do not end up with what amounts to a container with two parents.

If you decide to go that route, please let me know if you'd like to see any support to make that easier in example-drops-8-composer or elsewhere. It's fine if you want to keep using this image, although I'm not sure about the process for updating the bundled components.

**Comment by ataylorme** [comment]
Sorry for being late to the party. @arosboro have you considered using a separate Node Docker image for your Node build step? [CircleCI allows you to specify a Docker image per job](https://circleci.com/docs/2.0/custom-images/#using-your-image-on-circleci).

[I've found success running gulp that way](https://github.com/ataylorme/Advanced-WordPress-on-Pantheon/blob/master/.circleci/config.yml#L104:L129)

**Comment by arosboro** [comment]
@ataylorme I ended up just installing lando as part of my build process which provides the necessary tooling.  While I may still have projects that rely on this PR, I'm not sure I'm still using it widely anymore.

**Comment by ataylorme** [comment]
👍 Lando allows you to use a custom `Dockerfile` for any service. So you could maintain your own `Dockerfile` with everything you need and use it in Lando and a CI environment.

Alternatively, if [the Lando PHP Dockerfiles](https://hub.docker.com/u/devwithlando) have everything you need already you can use those directly in your CI environments. I've found [their `pantheon-appserver` image](https://hub.docker.com/r/devwithlando/pantheon-appserver) to have everything I need in a PHP image (proper extensions, Terminus, etc.). It is also well maintained and has tags for a variety of PHP versions.

@greg-1-anderson would you be open to a PR having the `Dockerfile` in this repo start from `devwithlando/pantheon-appserver` rather than `drupaldocker/php:7.2-cli`? The Lando image is closer to Pantheon's appservers.

**Comment by greg-1-anderson** [comment]
I don't want to conflate this docker image for one that is used as a local development environment. If `devwithlando/pantheon-appserver` allows us to build more components (e.g. produce css from SASS/LESS) and/or install Drupal on Circle to save time by running some tests there, then I'd consider it.

**Comment by ataylorme** [comment]
I guess intent was misplaced. The Lando Pantheon `Dockerfile` is closer to the Pantheon appserver containers than  `drupaldocker/php:72.-cli` but since we are not running Drupal or WordPress on CircleCI it isn't relevant.

**Comment by ataylorme** [comment]
Closing in favor of #27

**Pull request closed without merging**
